# Generated by Django 4.1.7 on 2023-03-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=100, verbose_name='英文名称'),
            preserve_default=False,
        ),
    ]
